import { TaskProvider } from '@/context/TaskContext'
import Header from './components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es-AR" className='w-screen h-screen'>
      <TaskProvider>
        <body className='w-full h-full'>       
        <Header/>
        {children}
        </body>
      </TaskProvider>
    </html>
  )
}
